#!/bin/sh
echo 'Making file homes...
'
#makes sbt expected folder structure
mkdir -p src/main/scala
mkdir -p src/test/scala
mkdir lib project target
echo 'OK
'
echo 'Making sbt happy
'
#writes build preferences required to run to build.sbt
echo 'name := "Stub"
version := "1.0"
scalaVersion := "2.11.7"' > build.sbt
echo 'OK
'
echo 'Making a stub-a-dub-dub
'
#writes a stub application to print Hello, homies
echo 'package hey.there.classmates 
object Main extends App {
     println("Hello, homies")
}
' > src/main/scala/Hello.scala
echo 'OK
'
echo 'if uncommented plugins, adding plugins'
#Next line is for the coverage plugin... if you want it, uncomment it.
#echo 'addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.5")' >> project/plugins.sbt
echo '
OK'

echo 'adding .gitignore (thanks @elliottpost)'
curl https://raw.githubusercontent.com/lucproglangcourse/processtree-scala/master/.gitignore > .gitignore
echo 'OK
'

echo '
Completed, make sure to count 5 OKs with no errors in them
you may now run: 
$sbt compile
$sbt run'
rm -f script
